SEO - 171884 - Page with Redirect Fix 1
syncfusion-content/uwp-docs pull request #371
Opened 2023-05-23 12:08 UTC by Thahira-Banu

Hi @Aishwarya-Ganesan 

I have made changes in the Page with Redirect Links by replacing redirect links.

Thanks & Regards

2023-05-23 12:09 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-171884-Page-with-redirect-fix](https://jenkins.syncfusion.com/job/Content/job/uwp-docs/191/console)**

2023-05-23 12:11 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-171884-Page-with-redirect-fix](https://jenkins.syncfusion.com/job/Content/job/uwp-docs/191/)<br/>**

2023-05-24 12:43 UTC, MallikaRK requested changes

2023-05-24 12:43 UTC, MallikaRK commented on uwp/RichTextBox/Comment.md
> +## Visibility of comment pane
Are you made this changes?

2023-05-25 07:25 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-171884-Page-with-redirect-fix](https://jenkins.syncfusion.com/job/Content/job/uwp-docs/195/console)**

2023-05-25 07:27 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-171884-Page-with-redirect-fix](https://jenkins.syncfusion.com/job/Content/job/uwp-docs/195/)<br/>**

2023-05-25 09:41 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-171884-Page-with-redirect-fix](https://jenkins.syncfusion.com/job/Content/job/uwp-docs/196/console)**

2023-05-25 09:43 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-171884-Page-with-redirect-fix](https://jenkins.syncfusion.com/job/Content/job/uwp-docs/196/)<br/>**

2023-06-01 08:14 UTC, MallikaRK requested changes
Commented

2023-06-01 08:14 UTC, MallikaRK commented on uwp/Charts/Series-old.md
> +---
Why do you create duplicate series.md file. Check and revert it.

2023-06-12 12:29 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-171884-Page-with-redirect-fix](https://jenkins.syncfusion.com/job/Content/job/uwp-docs/215/console)**

2023-06-12 12:31 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-171884-Page-with-redirect-fix](https://jenkins.syncfusion.com/job/Content/job/uwp-docs/215/)<br/>**

2023-06-20 09:20 UTC, Thahira-Banu commented
I have made changes in multiple PR's, so closed it.

2023-06-20 09:20 UTC, closed without merging