Seo-171884-Page-with-redirect-fix-2
syncfusion-content/uwp-docs pull request #372
Opened 2023-05-24 07:09 UTC by Thahira-Banu

Hi @Aishwarya-Ganesan 
I had made changes in page with redirect links by replacing redirecting urls.

Thanks & Regards

2023-05-24 07:10 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-171884-Page-with-redirect-fix-2](https://jenkins.syncfusion.com/job/Content/job/uwp-docs/192/console)**

2023-05-25 10:08 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-171884-Page-with-redirect-fix-2](https://jenkins.syncfusion.com/job/Content/job/uwp-docs/197/console)**

2023-05-25 10:10 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-171884-Page-with-redirect-fix-2](https://jenkins.syncfusion.com/job/Content/job/uwp-docs/197/)<br/>**

2023-06-01 08:17 UTC, MallikaRK requested changes
Commented

2023-06-01 08:17 UTC, MallikaRK commented on uwp/Charts/Series.md
> +![Colum SegmentSpacing support in UWP Chart](series_images/segmentspacing.png)
You make the UWP/Chart/Series.md file changes in the below PR too.
https://github.com/syncfusion-content/uwp-docs/pull/371/files
Which one is Final?

2023-06-01 08:17 UTC, MallikaRK commented on uwp/Charts/Series.md
> +![Colum SegmentSpacing support in UWP Chart](series_images/segmentspacing.png)
Seems both PR's are duplicate. Pleas check and share the Final PR.

2023-06-20 09:37 UTC, Thahira-Banu commented
I have made changes in multiple PR's , so closed it.

2023-06-20 09:37 UTC, closed without merging