SEO-171884-Page-with-Redirect-fix-3
syncfusion-content/uwp-docs pull request #373
Opened 2023-05-24 10:18 UTC by Thahira-Banu

Hi @Aishwarya-Ganesan 
I had made changes in the Page with Redirect links by replacing the redirecting urls.

Thanks & Regards,
Thahira Banu

2023-05-24 10:19 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-171884-Page-with-Redirect-fix-3](https://jenkins.syncfusion.com/job/Content/job/uwp-docs/193/console)**

2023-05-24 10:24 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-171884-Page-with-Redirect-fix-3](https://jenkins.syncfusion.com/job/Content/job/uwp-docs/193/console)**

2023-05-24 10:26 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-171884-Page-with-Redirect-fix-3](https://jenkins.syncfusion.com/job/Content/job/uwp-docs/193/)<br/>**

2023-05-25 10:45 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-171884-Page-with-Redirect-fix-3](https://jenkins.syncfusion.com/job/Content/job/uwp-docs/198/console)**

2023-05-25 10:45 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-171884-Page-with-Redirect-fix-3](https://jenkins.syncfusion.com/job/Content/job/uwp-docs/198/)<br/>**

2023-06-01 08:20 UTC, MallikaRK requested changes
Commented

2023-06-01 08:20 UTC, MallikaRK commented on uwp/Charts/Trendlines.md
> +![Trendlines in UWP Chart](Trendlines_images/uwp-charts-trendlines.png)
Change Image Folder Name to small casing.
<img width="414" alt="image" src="https://github.com/syncfusion-content/uwp-docs/assets/44014283/5342db49-720a-48b0-8e9f-0646d0f7da18">
Seems folder name contains small case letters, you should change the image folder name to small case.

2023-06-20 09:51 UTC, Thahira-Banu commented
I have made changes in multiple PR's , so i closed it.

2023-06-20 09:51 UTC, closed without merging