SEO-172815-UWP-controls
syncfusion-content/uwp-docs pull request #392
Opened 2023-06-14 08:27 UTC by Edithabich

Hi @MallikaRK ,
Have added the contents, please review.
Thanks.

Regards,
Edith.

2023-06-14 08:28 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO-172815-UWP-controls](https://jenkins.syncfusion.com/job/Content/job/uwp-docs/220/console)**

2023-06-14 08:36 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172815-UWP-controls](https://jenkins.syncfusion.com/job/Content/job/uwp-docs/220/console)**

2023-06-14 08:38 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172815-UWP-controls](https://jenkins.syncfusion.com/job/Content/job/uwp-docs/220/)<br/>**

2023-06-14 09:10 UTC, MallikaRK requested changes
Commented

2023-06-14 09:10 UTC, MallikaRK commented on uwp/AutoComplete/Getting-Started.md
> +N> You can refer to our [UWP AutoComplete feature tour](https://help.syncfusion.com/uwp/autocomplete/getting-started) page to know about its other groundbreaking feature representations. You can also
Hi @Edithabich , update feature tour page link. you have added UG page here. 
<img width="645" alt="image" src="https://github.com/syncfusion-content/uwp-docs/assets/44014283/6d2b87f1-3b89-4ff7-bb30-9b695853a6ed">

2023-06-14 09:10 UTC, MallikaRK commented on uwp/Numeric-TextBox/Getting-Started.md
> +[How to restrict the decimal values in SfNumericTextBox](https://www.syncfusion.com/kb/6957/how-to-restrict-the-decimal-values-in-sfnumerictextbox)
Update our latest KB link here.

2023-06-14 11:27 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172815-UWP-controls](https://jenkins.syncfusion.com/job/Content/job/uwp-docs/221/console)**

2023-06-14 11:28 UTC, Edithabich commented on uwp/Numeric-TextBox/Getting-Started.md
> +[How to restrict the decimal values in SfNumericTextBox](https://www.syncfusion.com/kb/6957/how-to-restrict-the-decimal-values-in-sfnumerictextbox)
Link updated

2023-06-14 11:28 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172815-UWP-controls](https://jenkins.syncfusion.com/job/Content/job/uwp-docs/221/)<br/>**

2023-06-15 06:55 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172815-UWP-controls](https://jenkins.syncfusion.com/job/Content/job/uwp-docs/223/console)**

2023-06-15 06:55 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172815-UWP-controls](https://jenkins.syncfusion.com/job/Content/job/uwp-docs/223/)<br/>**

2023-06-21 10:44 UTC, MallikaRK approved these changes
Approved

2023-06-22 10:55 UTC, Girija-Rajendran commented on uwp/AutoComplete/Getting-Started.md
> +N> You can refer to our [UWP AutoComplete feature tour](https://www.syncfusion.com/uwp-ui-controls/autosuggestbox) page to know about its other groundbreaking feature representations. You can also ex
[UWP AutoComplete](https://www.syncfusion.com/uwp-ui-controls/autosuggestbox) feature tour page..........

update latest content
<img width="607" alt="image" src="https://github.com/syncfusion-content/uwp-docs/assets/61148953/b76dc831-69ea-4bc5-ad36-d10eb586dc2e">

2023-06-23 13:04 UTC, Edithabich commented on uwp/AutoComplete/Getting-Started.md
> +N> You can refer to our [UWP AutoComplete feature tour](https://www.syncfusion.com/uwp-ui-controls/autosuggestbox) page to know about its other groundbreaking feature representations. You can also ex
resolved

2023-06-23 13:05 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172815-UWP-controls](https://jenkins.syncfusion.com/job/Content/job/uwp-docs/234/console)**

2023-06-23 13:06 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172815-UWP-controls](https://jenkins.syncfusion.com/job/Content/job/uwp-docs/234/)<br/>**

2023-06-23 13:31 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-172815-UWP-controls](https://jenkins.syncfusion.com/job/Content/job/uwp-docs/235/console)**

2023-06-23 13:32 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-172815-UWP-controls](https://jenkins.syncfusion.com/job/Content/job/uwp-docs/235/)<br/>**

2023-07-19 12:26 UTC, Aishwarya-Ganesan approved these changes
Changes are fine.

2023-07-19 12:26 UTC, merged