SEO-184285-UWP-Overview-Parmanent-Redirect-link
syncfusion-content/uwp-docs pull request #660
Opened 2024-08-20 13:48 UTC by Faith-Atieno

Title | Description
-- | --
|Task Category | Site Audit work|
|Content Task Link/Mail Screenshot | NA|
|Hotfix |https://github.com/syncfusion-content/blazor-docs/pull/4769|
|Ticket/Task link |https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/184285|
|Work link |https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B0C07BBB1-1233-47A7-818C-275A98FD0063%7D&file=Faith-%20Site%20Audit.xlsx&action=default&mobileredirect=true|

Title | Description
-- | --
|Task Category | Coverage Issues|
|Content Task Link/Mail Scr
Changes made | Reason for change
-- | --
| Page with redirect| To increase page performance |

2024-08-20 13:49 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-184285-UWP-Overview-Parmanent-Redirect-link](https://ci.syncfusion.com/job/Content/job/uwp-docs/48/console)**

2024-08-20 13:54 UTC, SyncfusionBuild commented
The CI [Job](https://ci.syncfusion.com/job/Content/job/uwp-docs/48/console) is already running for this Pull Request/Merge Approved with latest commit id. You cannot trigger the duplicate job for same.

2024-08-20 13:54 UTC, Faith-Atieno commented
rebuild

2024-08-20 13:57 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-184285-UWP-Overview-Parmanent-Redirect-link](https://ci.syncfusion.com/job/Content/job/uwp-docs/48/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/uwp-docs/48/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/uwp-docs/48/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/uwp-docs/48/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/uwp-docs/48/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/uwp-docs/48/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/uwp-docs/48/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/uwp-docs/48/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/uwp-docs/48/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**

2024-08-22 09:10 UTC, Yvone-Atieno requested changes
Commented

2024-08-22 09:10 UTC, Yvone-Atieno commented on uwp/Overview.md
> +			<a href="/word-library/net/overview">DocIO</a><br/><br/>
Revert the changes made in this md

2024-08-22 09:30 UTC, Faith-Atieno commented on uwp/Overview.md
> +			<a href="/word-library/net/overview">DocIO</a><br/><br/>
Changes reverted hence closing this PR

2024-08-22 09:30 UTC, closed without merging

2024-08-22 09:30 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-184285-UWP-Overview-Parmanent-Redirect-link](https://ci.syncfusion.com/job/Content/job/uwp-docs/49/)<br/>Technical Error(s): 0<br/>Spelling Error(s): 0<br/>Image Alt Text Error(s): [0](https://ci.syncfusion.com/job/Content/job/uwp-docs/49/artifact/cireports/ImageValidation/AltTextValidation.html)<br/>Image Size Error(s): [0](https://ci.syncfusion.com/job/Content/job/uwp-docs/49/artifact/cireports/ImageValidation/ImageSizeValidation.html)<br/>Image Name Error(s): [0](https://ci.syncfusion.com/job/Content/job/uwp-docs/49/artifact/cireports/ImageValidation/ImageNameValidation.html)<br/>FT Layout Syntax Error(s): [0](https://ci.syncfusion.com/job/Content/job/uwp-docs/49/artifact/cireports/FTLayoutSyntaxValidation/FTStructureValidation.html)<br/>Front matter Error(s): [0](https://ci.syncfusion.com/job/Content/job/uwp-docs/49/artifact/cireports/FrontMatterValidation/FrontMatterValidation.html)<br/>File Path Error(s): [0](https://ci.syncfusion.com/job/Content/job/uwp-docs/49/artifact/cireports/FilePathValidation/FilePathValidation.html)<br/>CodeSnippet File Path Missing Error(s): [0](https://ci.syncfusion.com/job/Content/job/uwp-docs/49/artifact/cireports/CodeSnippetFilePathValidation/CodeSnippetFilePathValidation.html)<br/>Toc Anchor Tags Validation Error(s): [0](https://ci.syncfusion.com/job/Content/job/uwp-docs/49/artifact/cireports/AnchorTagsValidation/AnchorTagsValidation.html)<br/>**